import { Inter } from "next/font/google";
import "@app/styles/globals.sass";
import { AuthProvider } from "@app/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
            <html lang="en">
                <body>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </body>
            </html>
    );
}
